### ISSUE TITLE
Filter by workItemID

### ISSUE THREAD

**Issue by mrmar096** [BlueBasher/WorkItemUpdater#100]
Hello,

Thanks for the useful task. Please i need a filter for workItemReferences, so please can you add to the input task a property for update specific workItem by workitemID?

Regards,

Mario.

**Comment by BlueBasher** [comment]
You could do that with workitemsSource and setting it to a query that filters for the workitemID.

**Comment by brynhh** [comment]
@BlueBasher I don't think this is an answer. We use pipelines and releases for Power Platform solutions and as there's no code to work with, work items are not linked to these. Therefore, I've built a query that filters on area path, state and work item type and use that query in your tool to then update the items in the release. However, it means if there's many items in that state, they'll all get updated by releases that are nothing to do with them, so I need a way to filter by ID, as we can specify those IDs in a variable in the pipeline which we pass the value of to the release.

A query wouldn't do this, as it would have fixed IDs within it, you cannot dynamically pass filters to a query. What you're suggesting means the query needs updating every time a pipeline/release is run, which is not efficient.
