### ISSUE TITLE
No dropdown values are shown in UI view

### ISSUE THREAD

**Issue by omid1234** [BlueBasher/WorkItemUpdater#106]
Since some days the values for "Work Item Type" and "Work Item State" does not provide any common values (e.g. "User Story" and "Active")

The console shows just a HTTP 400 Error and it is not shown anything which is needed to use the extension in the ui mode.

Thanks for your work and a great day for you :)

![dropdown_workItemUpdater](https://user-images.githubusercontent.com/1710455/186850186-60141834-db6a-4db6-b4a5-d9409f241282.png)

![console_error_workItemUpdater](https://user-images.githubusercontent.com/1710455/186850214-83801234-5358-48dd-bfe6-926aa5e55885.png)

**Comment by pbcahill** [comment]
I get the same exact behavior, the task is no longer usable since we cannot select a Work Item type.

**Comment by SunDevils0** [comment]
I am getting the same. I was able to use this on 7/26/2022 with no issues. I tried adding it yesterday on a different release pipeline, and I am getting the same behavior. Also cannot modify that value on any existing pipelines where the task has been previously added.
