### ISSUE TITLE
breaks on kanban columns and lane

### ISSUE THREAD

**Issue by joelkaufman** [BlueBasher/WorkItemUpdater#12]
since kanban columns / lane is a dynamic field, constructed as {boardID}.Kanban.Column
if the workitem was never in that board as with new workitems or old workitems that was created before adding the kanban board, the script will break because the field isn't defined, 
there needs be a check if the field exists and if doesn't skip

**Comment by BlueBasher** [comment]
Updating the kanban columns has been modified so it better verifies if the column exists. A new version (1.4.716) has been deployed that should fix this.
