### ISSUE TITLE
Still getting "Cannot validate argument on parameter 'Result'. The argument "Error updating workitems" does not belong to the set "Succeeded,SucceededWithIssues,Failed,Cancelled,Skipped" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again." despite #2 being closed

### ISSUE THREAD

**Issue by RachelAmbler** [BlueBasher/WorkItemUpdater#13]
AFAIK I'm on the latest build (unsure on quite how to check), however the errors reported in #2 are still being received when I try to use thin in a new test TFS 2017 Update 2 Git based project.

**Comment by joelkaufman** [comment]
it might be related to #12

**Comment by kperry10893** [comment]
I'm also getting 
##[error]Cannot validate argument on parameter 'Result'. The argument "Error updating workitems" does not belong to the set "Succeeded,SucceededWithIssues,Failed,Cancelled,Skipped" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.

Am using TFS 2017 Update 2.

**Comment by pluque** [comment]
same same here

**Comment by BlueBasher** [comment]
A bug with falsely updating a column that did not exists, was the reason for this error. A new version (1.4.716) has been deployed that should fix this.

**Comment by kperry10893** [comment]
I'm still seeing the issue when using version 1.4.716

**Comment by kmusick** [comment]
Seeing this error attempting to move Tasks to Done state
