### ISSUE TITLE
workitemsSource  - how "And a query" must be understood

### ISSUE THREAD

**Issue by FeelTheWay** [BlueBasher/WorkItemUpdater#132]
Hi,

The workitems Source can be 
"WorkItems linked to the Build/Release and a WorkItem Query"

What does the "AND" mean ? 

"All ticket inside Build/release" + "All tickets inside the Query"
or
"All tickets inside build release also include inside the Query" ?

Is it possible to add a filter "ticket custom field is empty" or something like that please ?

**Comment by BlueBasher** [comment]
It's both, so included in Build and also included in query results.
For the empty value check you could create a query.
