### ISSUE TITLE
Update State of Work Item in Release

### ISSUE THREAD

**Issue by EyeDragon** [BlueBasher/WorkItemUpdater#133]
I'm using this one to update State of Work Item in Release and this is my configuration

![image](https://github.com/BlueBasher/WorkItemUpdater/assets/40334043/2ace42af-2971-4237-859d-47f9c5f5ee5f)

However, most of time when it is triggered, it can found items but can't update the state

![image](https://github.com/BlueBasher/WorkItemUpdater/assets/40334043/4c33eaae-d80d-4cee-9f83-0a99aae7abc5)

Could you help me this one?

**Comment by BlueBasher** [comment]
I believe the workItemType list should be without spaces.
