### ISSUE TITLE
How to use query

### ISSUE THREAD

**Issue by JulienDryepondt** [BlueBasher/WorkItemUpdater#134]
Hello,

I have problem to find any example that would help me to configure this task on my project.
I don't understand how is working the parameter "workitemsSourceQuery". On every try i get "Could not find query"

Here's the code i put : 
- job: UpdateWorkItem
        condition: not(failed('ParseDeploymentResult'))
        dependsOn: ParseDeploymentResult
        timeoutInMinutes: 0
        continueOnError: "false"
        steps:
          - task: WorkItemUpdater@2
            inputs:
              workitemsSource: "Query"
              workitemsSourceQuery: "SELECT [system.Id] FROM WorkItems"
              workItemType:  "User Story,Task,Bug"
              workItemState: "Active"
              failTaskIfNoWorkItemsAvailable: "true"

I tried too to reference a query from the inside of the Azure project.
Can someone help me to understand how it works please ?

Thanks

**Comment by BlueBasher** [comment]
workitemsSourceQuery should either be the Id of a query (find it in the url) or the name including the folder path.
