### ISSUE TITLE
Cannot read property 'forEach' of null since version 3.0.80

### ISSUE THREAD

**Issue by KoosMos** [BlueBasher/WorkItemUpdater#147]
Hi,
Since the new release 3.0.80, I have this issue :
![image](https://github.com/user-attachments/assets/5b3f8051-e340-421e-baf6-29b9ae979eea)

**Comment by k0perX-X** [comment]
The same issue. 

Settings:
![image](https://github.com/user-attachments/assets/fbe2ced9-cf72-4804-be23-035b6d3db65d)
![image](https://github.com/user-attachments/assets/e6fa7881-0527-4b8c-baee-d836a52dff63)

**Comment by kannan-cidc** [comment]
@BlueBasher  - have fixed this issue and raised a PR can you please approve it ? 

https://github.com/BlueBasher/WorkItemUpdater/pull/151

**Comment by k0perX-X** [comment]
> @BlueBasher - have fixed this issue and raised a PR can you please approve it and publish the new version ?
> 
> #151
It didn't help, the same error remained
![image](https://github.com/user-attachments/assets/4a3e561e-1ed4-4bf6-acea-bda056a1efa3)
![image](https://github.com/user-attachments/assets/bacf60af-5c8a-4d09-a62c-ba512274f13f)

**Comment by BlueBasher** [comment]
I've deployed a new version that reverted the failing code. Sorry for the inconvenience.
