### ISSUE TITLE
Error: fromBuildId or toBuildId is null. Supply a valid value and try again. since version 3.0.80

### ISSUE THREAD

**Issue by vitapyh** [BlueBasher/WorkItemUpdater#148]
Hi
Since the new release 3.0.80, I have this issue :
Error: fromBuildId or toBuildId is null. Supply a valid value and try again.

![image](https://github.com/user-attachments/assets/c767cc88-fb8f-4fa6-8831-6d68f61e0daa)

**Comment by hemsleyk** [comment]
+1

**Comment by fjre** [comment]
+1, quite annoying that this isn't fixed yet.

**Comment by jsiljeg** [comment]
+1

**Comment by hemsleyk** [comment]
Not fixed after PR 151

**Comment by BlueBasher** [comment]
I've deployed a new version that reverted the failing code. Sorry for the inconvenience.

**Comment by lktraser** [comment]
@vitapyh I would like to get the code running again for multi artifact release pipeliens. Could you tell me which parameters you used when you got this error? I'm running that version in production and have not seen this yet.
