### ISSUE TITLE
PR#62 fixing work item search with multiple artifacts broke the task from working

### ISSUE THREAD

**Issue by TrentBie** [BlueBasher/WorkItemUpdater#149]
this PR broke the task from working when there are multiple artifacts.

Now it just says no work items found to update.

When release has single artifact task works fine

**Comment by mrpolaris** [comment]
@BlueBasher   And updates to get this task working again

**Comment by BlueBasher** [comment]
I've deployed a new version that reverted the failing code. Sorry for the inconvenience.

**Comment by TrentBie** [comment]
Thank you for fixing this.

Trent Bielejeski
Senior DevOps Engineer

Bell Bank
3100 13th Avenue South | Fargo, ND 58103
Phone 701.237.2839 | Mobile 218.304.1093
***@***.******@***.***> | www.bell.bank<https://bell.bank/> | Member FDIC
A Local and National Award-Winning Company<https://bell.bank/awards>

Bell cares about safeguarding your information. Never email or text documents that contain personal or sensitive information. Please contact me to discuss possible options I can provide to securely upload documentation that may contain personal information.

**Comment by lktraser** [comment]
@TrentBie is this closed for you? if I read your original text correctly your issue is that the multi artifact pipelines are broken again correct?

> this PR broke the task from working when there are multiple artifacts.
> 
> Now it just says no work items found to update.
> 
> When release has single artifact task works fine

**Comment by TrentBie** [comment]
Yes the code was reverted and now the task works with multiple artifacts

Trent Bielejeski
Senior DevOps Engineer

Bell Bank
3100 13th Avenue South | Fargo, ND 58103
Phone 701.237.2839 | Mobile 218.304.1093
***@***.******@***.***> | www.bell.bank<https://bell.bank/> | Member FDIC
A Local and National Award-Winning Company<https://bell.bank/awards>

Bell cares about safeguarding your information. Never email or text documents that contain personal or sensitive information. Please contact me to discuss possible options I can provide to securely upload documentation that may contain personal information.
