### ISSUE TITLE
workitemLimit not working with sourcequery

### ISSUE THREAD

**Issue by crulat** [BlueBasher/WorkItemUpdater#153]
I have a following configuration and newest version (3.0.88) of WorkItemUpdater. During every run it seems that "workitemLimit" is not used at all. Latest run changed every PBI which "workiemsSourceQuery" as able to find. Have I configured something wrong :-D
My config:

        - task: WorkItemUpdater@3
          inputs:
            workitemsSource: "Query"
            workitemsSourceQuery: "XXX"
            workitemLimit: 5
            workItemType: "Product Backlog Item"
            updateAssignedTo: "Never"
            workItemState	: "Test"

**Comment by rdehouss** [comment]
https://github.com/BlueBasher/WorkItemUpdater/blob/main/src/WorkItemUpdater.ts#L208

The parameter `workitemLimit` is only used for `getBuildWorkItemsRefs`, not for the Query

**Comment by crulat** [comment]
@rdehouss Thank you so much for clarifying this. Case closed :-)
