### ISSUE TITLE
Should this work for all project templates?

### ISSUE THREAD

**Issue by carlfarmer** [BlueBasher/WorkItemUpdater#18]
Hi,

This looks awesome, but it doesn't seem to want to successfully update Task items in the Agile process template.

I specifically set it to update Task items where the status is Active and set it to Closed. The task runs in the CI/CD process but nothing gets updated.

Thank you.

**Comment by BlueBasher** [comment]
A new version has been published with the changes from #20 With this change the extension can also be used in Agile Template projects.
