### ISSUE TITLE
Error changing Kanban Board Column 

### ISSUE THREAD

**Issue by Norticaranda** [BlueBasher/WorkItemUpdater#25]
Hi

Change this Field "/fields/$($_)" not change the kanban board column and generate a UpdateWorkItemAsync error.

        if ($workItemKanbanState -ne "" -and $kanbanColumn -ne "" -and $kanbanColumn -ne $null) {
            $kanbanColumn.Split(" ") | ForEach-Object { 
                $columnDoneOperation = New-Object Microsoft.VisualStudio.Services.WebApi.Patch.Json.JsonPatchOperation
                $columnDoneOperation.Operation = [Microsoft.VisualStudio.Services.WebApi.Patch.Operation]::Add
                $columnDoneOperation.Path = "/fields/$($_)"
                $columnDoneOperation.Value = $workItemKanbanState
                $patch.Add($columnDoneOperation)
                Write-VstsTaskDebug -Message "Patch: $($columnDoneOperation.Path) $($columnDoneOperation.Value)"
            }
        }

Thanks

**Comment by BlueBasher** [comment]
I just tested it and I can update the Kanban Board Column of a WorkItem without an error.
Would it be possible you show what parameters you entered in the WorkItem Updater task? And potentially also post the build log output of the task?
