### ISSUE TITLE
Update user story when build successful 

### ISSUE THREAD

**Issue by olva** [BlueBasher/WorkItemUpdater#27]
Hi, 
    I am trying your task item on VSTS to update user story but I can't attach the build to a user story, in Work Item type  window I can only choose the type of the user story but I can't choose which user story to link to, can you help set up this build task on VSTS to update the progress of the build definition to be reflected on the user story ?

**Comment by BlueBasher** [comment]
The idea of the task is that you link a WorkItem to a PullRequest. When a Build runs as part of the PullRequest the task will then find to linked WorkItem(s) and update them with the parameters you specified in the task.
Have a look at the [Overview](https://github.com/BlueBasher/WorkItemUpdater/blob/master/src/overview.md) to see how that works.
