### ISSUE TITLE
Release failing due to WorkItemUpdater Exception

### ISSUE THREAD

**Issue by tfillerup** [BlueBasher/WorkItemUpdater#29]
I have set up a release in VSTS and at the end of the workflow I am trying to use WorkItemUpdater to move work items from one state to another.  For some reason, I am getting an exception when running that task.
I have attached the log file and a screenshot of my task settings.  Please let me know if I am doing something wrong in my setup or how I can get this to work.

Thank You

<img width="655" alt="capture" src="https://user-images.githubusercontent.com/5374213/41294982-9a43fdec-6e16-11e8-91ee-e55ba37713bc.PNG">

[tasklog_10.log](https://github.com/BlueBasher/WorkItemUpdater/files/2094315/tasklog_10.log)

**Comment by BlueBasher** [comment]
Your task settings look fine to me.
I do see the StackOverflow error in the logfile, but there's not enough info in there to resolve the issue.
Would it be possible for you to edit your workflow and add a variable "system.debug", set the value to "true" and run the release again?
Then there should be more info in the logfile and hopefully enough to be able to fix the issue.

**Comment by tfillerup** [comment]
Here is the full log.
[tasklog_10 (1).log](https://github.com/BlueBasher/WorkItemUpdater/files/2100217/tasklog_10.1.log)

Thank You

**Comment by BlueBasher** [comment]
In the logging it shows the BuildId: ##[debug]BUILD_BUILDID: 'c26e7eb4ebda85b88f0c51af134be6a841ef14c9'
This is coming from the VSTS variable Build.BuildId. The WorkItem Updater (and the underlying API calls) is expecting this Build to be an integer.
From within the release, if you open the link to the related build, can you see in the url what the BuildId is? The Url should contain "_build/results?buildId=...."

I checked multiple VSTS accounts and Projects and there the BuildId is always an integer. Do you have any idea what could be different in your VSTS account so the BuildId is c26e7eb4ebda85b88f0c51af134be6a841ef14c9?

**Comment by tfillerup** [comment]
That was the problem.  I was referring to a branch not a build as my artifact.  I changed it to refer to a build and all is good now. Thank you for your help.
