### ISSUE TITLE
No items getting picked for update

### ISSUE THREAD

**Issue by netmailgans** [BlueBasher/WorkItemUpdater#34]
Attached the log taken after setting system.debug as true.
[tasklog_8.log](https://github.com/BlueBasher/WorkItemUpdater/files/2148497/tasklog_8.log)

I am using TFS 2017 On-Prem. Let me know if you need more details. Below is the screenshot for the WorkItemUpdater task;
![image](https://user-images.githubusercontent.com/40688059/42082716-57223716-7ba6-11e8-921f-bd72523f45c0.png)

Thanks in advance.

**Comment by BlueBasher** [comment]
There was an issue in VSTS with the QueryControl. I changed it into a string input, so you can directly enter the full name of the query. So something like "Shared Queries\My Query"

There is no error or anything in the logfile, but I would have expected some more debug logging and for some reason that is not there. I've added more logging to the task to help to resolve this.

I just merged #35 which also includes these 2 items. Could you try again with the latest version 2.4.784?

**Comment by netmailgans** [comment]
Thank you very much, Marco van Kimmenade. Sorry for the delay in my response. I was in mid of upgrading our TFS from 2017 to 2018; and wanted to give you my latest updates. Apparently, your solution worked like a charm with TFS 2018. Do you still want me to take the latest? Please advise.

**Comment by BlueBasher** [comment]
There are no further changes in the latest version, so if the version you have works, you could stay with that one.
Obviously newer versions will/should also keep working so if I add new features in the future you should be able to upgrade without any issues.
