### ISSUE TITLE
Plugin not working to update the state

### ISSUE THREAD

**Issue by calvinmichel** [BlueBasher/WorkItemUpdater#39]
I have tried in both the Build and Release functionality to update a defect work item state.  I am using TFS 2017 On Prem. There are no mandatory fields required in the workflow to transition to this state.  I get the error below, even though the State shows up in the list to be chosen.  It is also a valid state from Resolved (current state).

##[error]Error: The field 'State' contains the value 'Deployed To Test' that is not in the list of supported values
![workitemupdater_validstate](https://user-images.githubusercontent.com/20405266/45324473-c5257900-b53d-11e8-8a95-1505b6441384.PNG)

**Comment by peretiatko** [comment]
In VSTS is same error

**Comment by BlueBasher** [comment]
How have you configured the task?
Are you sure that the WorkItem Types you selected can actually have the "Deployed To Test" state?
In the configuration of the task you will always see all available WorkItem States. It is not filtered by the WorkItem Types you selected.

**Comment by peretiatko** [comment]
> Are you sure that the WorkItem Types you selected can actually have the "Deployed To Test" state?
In VSTS - that was my mistake. Thank`s a lot!
