### ISSUE TITLE
Update workitems of "skipped" releases

### ISSUE THREAD

**Issue by DeluxZ** [BlueBasher/WorkItemUpdater#4]
When using the task in a release it will only update the workitems linked to the release.
![image](https://user-images.githubusercontent.com/540033/27948610-b223db3a-62fa-11e7-8bf7-6bff4126bc1a.png)
In the case above the task will not update the workitems linked in Release-135. Is it possible to check per environment which workitems are deployed with previous release (like the Compare in Work items)?
![image](https://user-images.githubusercontent.com/540033/27948733-2f1961f0-62fb-11e7-929b-2f7c1735cf37.png)

**Comment by BlueBasher** [comment]
Need to investigate how to determine what the previous release Id was and what Api to use to query the WorkItems associated since that release.
 Any help with this investigation would be appreciated @DeluxZ ;)

**Comment by DeluxZ** [comment]
I think you should be able to get the previous release id while iterating through the [list of releases](https://www.visualstudio.com/en-us/docs/integrate/api/rm/releases#get-a-list-of-releases). I guess a filter on status is a good idea and expand the environments. In the environments look for the environment name which triggers the work item updater task and check the status field till the first with status == succeeded and use the id of the release in the next API call.

The compare button in VSTS does a call to https://{account}.vsrm.visualstudio.com/{project}/_apis/Release/releases/{currentReleaseId}/workitems?baseReleaseId={releaseIdToCheck}&$top=250 which results in a list of workitem ids.

**Comment by BlueBasher** [comment]
It took some time but... finally there's now an option to include the workitems from 'skipped' releases.
This is implemented in #33
