### ISSUE TITLE
Any docs of how to set this up?

### ISSUE THREAD

**Issue by theCorb1nator** [BlueBasher/WorkItemUpdater#44]
Hi, any docs on how to configure this plugin,

i would like it so that when a  PR is completed that a work item state is updated to "Testing" is this possible? 

Thanks

Corbin

**Comment by ruaan** [comment]
Same here

**Comment by BlueBasher** [comment]
The documentation that there is, is what you see in the Azure DevOps Marketplace.
The task should be pretty self-explanatory, for your use case you should first select the WorkItemTypes that you want to update. Next set the WorkItemState to "Testing".
The task will then look for WorkItems linked to the Build or Release and update those accordingly. These WorkItems will be linked to the Build by using a PR and link the WorkItems there.

**Comment by theCorb1nator** [comment]
Figured it our thanks :) , great library btw
