### ISSUE TITLE
Feature Request: Add flag that if the task cant find work items it will fail

### ISSUE THREAD

**Issue by BlueBasher** [BlueBasher/WorkItemUpdater#50]

**Comment by bathenme** [comment]
hi,
add pull request for this can you approve?

**Comment by BlueBasher** [comment]
Hi,
apologies for the delay, overlooked the PR. I added a few comments in the PR. If you could look at those then I will definitely approve your PR.
Thanks!

**Comment by BlueBasher** [comment]
Implemented in PR #52
