### ISSUE TITLE
Local Issuer Certifcate on DevOps Server

### ISSUE THREAD

**Issue by cfs77** [BlueBasher/WorkItemUpdater#53]
Hi,

with version 2 of the build task I get this error. When I switch back to version 1 the error doesn't appear.
I think it's related to my company internal certifcate, isn't it?

Best regards 
carsten

![image](https://user-images.githubusercontent.com/37112783/66647874-5af07380-ec2a-11e9-93bd-38b85b831577.png)

**Comment by asticha** [comment]
Same error, any solution? THX

**Comment by BlueBasher** [comment]
My guess would be that this has indeed something to do with a local certificate. The difference between V1 and V2 is that V1 was written in Powershell and V2 is written in node.js.
The WorkItemUpdater task itself has no knowledge of certificates.
