### ISSUE TITLE
Build Link not added: "Build ### already linked to WorkItem ###"

### ISSUE THREAD

**Issue by markjsc** [BlueBasher/WorkItemUpdater#58]
Greetings!

I'm using WorkItem Updater in a Build to change the State of a custom Work Item type and I would also like it to create the link from the Build to the Work Item.

I'm using a Query as the source and changing the State is working as expected. But **the Build Link is never created**. The Work Items do not currently have any visible links (Parent, Related Work Items, Development, etc) prior to running the build.

I'm seeing this in the build output:
```
Using Query as WorkItem Source
##[debug]Found queryId 0def1c63-1ba0-4b8d-8c79-bd848f76ebcb from QueryName Shared Queries/AssetChanges_AssetsTransferred
##[debug]Loop workItemsRefs
##[debug]Found WorkItemRef: 14606
Found WorkItem: 14606
##[debug]Setting assignedTo to requester for build "Mark Johnston".
##[debug]Updating  WorkItem: 14606
Updating WorkItem 14606
##[debug]Found KanbanLane: 
##[debug]Found KanbanColumn: 
##[debug]Found KanbanColumnDone: 
Patch: /fields/System.State Closed
Build 5863 already linked to WorkItem 14606
```
I see the last line showing that the Build is already linked to the Work Item. It looks like the test for `buildRelation` is returning true:
https://github.com/BlueBasher/WorkItemUpdater/blob/a3e1500a9edbe650b6781027133664cb298fb215/src/WorkItemUpdater/WorkItemUpdater.ts#L260

(Apologies - I haven't taken time to set up a development environment to be able to debug this and propose a solution myself.)

Any ideas? Can I provide any additional information to help track this down?

Thanks for taking the time and effort to share such a useful utility with the community!!

-Mark

**Comment by Galad** [comment]
@markjsc 
Hello, I ran into the same issue. I submitted a PR, hope it will be merged soon :)

**Comment by markjsc** [comment]
> @markjsc
> Hello, I ran into the same issue. I submitted a PR, hope it will be merged soon :)

Bravo, @Galad! Thank you for taking the time to do this!!
