### ISSUE TITLE
You don't have permissions to bypass rules permission

### ISSUE THREAD

**Issue by pradeepyerramothu** [BlueBasher/WorkItemUpdater#59]
I set up the workitemupdater task on a release pipeline and checked the "Bypass rules" checkbox on the task. but i get the following error.

![image](https://user-images.githubusercontent.com/45051333/73277842-b6824500-41b8-11ea-9209-68a1eb63dc55.png)

I am not sure which user the error message is referring to. Is it the user that triggered the release or the agent that's performing the deployment. 

Please note that we have policies setup on workitems.

**Comment by BlueBasher** [comment]
The agent that is performing the pipeline is the account that does the actual update. So typically it is the Build Service Account.
