### ISSUE TITLE
Build link is incorrect

### ISSUE THREAD

**Issue by Galad** [BlueBasher/WorkItemUpdater#63]
When linked to the work item the build id is always "$buildId" instead of the actual build number
![image](https://user-images.githubusercontent.com/2237019/77650318-9ded9b80-6f6b-11ea-90cb-c6d2257422ce.png)

This result in an error in the work item:
![image](https://user-images.githubusercontent.com/2237019/77650427-c70e2c00-6f6b-11ea-95a2-9094d98ff2c6.png)

Version: 2.5.795

**Comment by BlueBasher** [comment]
Thanks for the PR. The new version is now available with version number 2.5.797
