### ISSUE TITLE
Work with the PR's related workitems only

### ISSUE THREAD

**Issue by sadedil** [BlueBasher/WorkItemUpdater#68]
Hi Blue,

I've used the WorkItemUpdater and it works perfectly. But I have a situation and a question.

I just want to update only workitems related to Pull Request which I'm currently merging. If i use `workitemsSource: 'Build'` all unrelated work items updating because of our mono repo approach. For example the workitems related to frontend shown in backend pipeline.

Is there any way to deal with this problem? For example can I use `workitemsSource: 'Query'` and get the correct work items only related with active PR, or third `workitemsSource` can be implemented?

I need your comments.

Thanks.

**Comment by BlueBasher** [comment]
I don't believe there is a way can create a query that uses the buildId as a paramater.
The Build workItemSource uses the Azure DevOps API to get all workitems related to that build. This is the same API Azure DevOps in their website as well. If you get all unrelated in WorkItemUpdater, then they should also appear in the build overview.
