### ISSUE TITLE
Deprecated dependencies

### ISSUE THREAD

**Issue by abousias** [BlueBasher/WorkItemUpdater#71]
@BlueBasher thanks for the extension, very helpful. 
Do you have any plans to switch to the latest npm packages from MS?

https://www.npmjs.com/package/vso-node-api
https://www.npmjs.com/package/vsts-task-lib

These 2 have been replaced by:

https://www.npmjs.com/package/azure-devops-node-api
https://www.npmjs.com/package/azure-pipelines-task-lib

**Comment by abousias** [comment]
Oh I see now that #67 is addressing the issue correct?

**Comment by abousias** [comment]
Although only one of the 2 packages is changed in #67.

This one is still the deprecated one:

https://github.com/BlueBasher/WorkItemUpdater/pull/67/files#diff-bd5c42b5fbc915c88a5c1640d3a2b84aR1

**Comment by BlueBasher** [comment]
Merged the PR #67 that solves this.
