### ISSUE TITLE
Specify "Assigned to"-user

### ISSUE THREAD

**Issue by BlueBasher** [BlueBasher/WorkItemUpdater#9]
Add the ability to assign to a specific user rather than just the requester of the build

**Comment by philcart** [comment]
Yes, this would be great option. It's the one part missing in our automated release pipeline. The developer has to manually re-assign the work item across to the UAT team.

**Comment by BlueBasher** [comment]
A new version has been published with the changes from #20
With this change there are new Build-Task paramters, making it possible to configure the Build-Task to update the AssignedTo field using a fixed user.
